menu:
- {name: 'sobre fnuc', url: '/sobre_fnuc'}
- {name: 'grupos', url: '/grupos'}
- {name: 'boletines', url: '/boletines'}
- {name: 'noticias', url: '/publications'}
#- {name: 'cv', url: '/cv'}
#- {name: 'contact', url: '/contact'}

grupos:
- {name: 'GFN-UCM', title: 'Grupo de Física Nuclear', department: 'EMFTEL', institution: 'Universidad Complitense de Madrid', institution_address: 'Facultad de Ciencias Físicas, Plaza de Ciencias 1, 28040 Madrid', image: 'assets/img/UCM.png', url: 'GFN-UCM'}

boletines:
- {name: '2023', url: '2023'}
- {name: '2024', url: '2024'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
